[files]
extend-exclude = [
    # ignore typos in c library source code
    "bindings/**/*.{c,h,inl,cmake}",
    # ignore typos in the bindgen wrappers
    "bindings/**/bindings/*",
]

[default.extend-words]
mosquitto = "mosquitto"
