[package]
name = "beluga"
version = "0.1.0"
publish = false
authors = [
    "Simon Berger <simon.berger@inomotech.com>",
    "Silvestr Predko <silvestr1994@gmail.com>",
]
edition = "2021"
rust-version = "1.74"
license = "MIT OR Apache-2.0"
repository = "https://github.com/inomotech-foss/beluga"
description = """
Crate designed to simplify the integration of AWS IoT functionality into your Rust applications.
This crate serves as a wrapper around the AWS IoT SDK,
providing a convenient and idiomatic Rust interface for developers working with AWS IoT services.
"""

[dependencies]
aws-c-common-sys = { git = "https://github.com/inomotech-foss/aws-iot-device-sdk-rust.git", branch = "restructure" }
aws-iot-device-sdk-cpp-sys = { git = "https://github.com/inomotech-foss/aws-iot-device-sdk-rust.git", branch = "restructure" }
crossbeam = "0.8"
futures = "0.3"
itertools = "0.12"
log = "0.4"
parking_lot = "0.12"
pin-project = "1"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "chrono"] }

[build-dependencies]
aws-c-builder = { git = "https://github.com/inomotech-foss/aws-iot-device-sdk-rust.git", branch = "restructure" }
cc = { version = "1", features = ["parallel"] }
