[workspace]
members = ["beluga"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/workspaces.html

[workspace.package]
authors = [
    "Silvestr Predko <silvestr1994@gmail.com>",
    "Simon Berger <simon.berger@inomotech.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.74"
repository = "https://github.com/inomotech-foss/beluga"
publish = false

[workspace.dependencies]
rumqttc = "0.24"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures-util = "0.3"
thiserror = "1"
tokio = "1"
tracing = "0.1"
