[workspace]
members = ["bindings/*", "packages/*"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/workspaces.html

[workspace.package]
authors = [
    "Silvestr Predko <silvestr1994@gmail.com>",
    "Simon Berger <simon.berger@inomotech.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.74"
repository = "https://github.com/inomotech-foss/aws-iot-device-sdk-rust"
publish = false

[workspace.dependencies]
aws-c-auth-sys = { path = "bindings/aws-c-auth-sys" }
aws-c-builder = { path = "bindings/aws-c-builder" }
aws-c-cal-sys = { path = "bindings/aws-c-cal-sys" }
aws-c-common-sys = { path = "bindings/aws-c-common-sys" }
aws-c-compression-sys = { path = "bindings/aws-c-compression-sys" }
aws-c-event-stream-sys = { path = "bindings/aws-c-event-stream-sys" }
aws-c-http-sys = { path = "bindings/aws-c-http-sys" }
aws-c-io-sys = { path = "bindings/aws-c-io-sys" }
aws-c-iot-sys = { path = "bindings/aws-c-iot-sys" }
aws-c-mqtt-sys = { path = "bindings/aws-c-mqtt-sys" }
aws-c-s3-sys = { path = "bindings/aws-c-s3-sys" }
aws-c-sdkutils-sys = { path = "bindings/aws-c-sdkutils-sys" }
aws-checksums-sys = { path = "bindings/aws-checksums-sys" }
aws-crt-cpp-sys = { path = "bindings/aws-crt-cpp-sys" }
aws-iot-device-sdk-sys = { path = "bindings/aws-iot-device-sdk-cpp-sys", package = "aws-iot-device-sdk-cpp-sys" }

anyhow = "1"
aws-lc-sys = "0.13"
bindgen = "0.69"
cmake = "0.1"
core-foundation = "0.9"
libc = "0.2"
s2n-tls-sys  = "0.1.0"
schannel = "0.1"
security-framework = "2"
