unstable_features = true

format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Upper"
imports_granularity = "Module"
normalize_comments = true
group_imports = "StdExternalCrate"
wrap_comments = true
