[package]
name = "aws-c-builder"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
generate-bindings = ["dep:bindgen"]

[dependencies]
bindgen = { workspace = true, optional = true }
cc.workspace = true
