[package]
name = "beluga"
version = "0.1.0"
publish = false
authors = [
    "Simon Berger <simon.berger@inomotech.com>",
    "Silvestr Predko <silvestr1994@gmail.com>",
]
edition = "2021"
rust-version = "1.74"
license = "Apache-2.0"
repository = "https://github.com/inomotech-foss/beluga"
description = """
Crate designed to simplify the integration of AWS IoT functionality into your Rust applications.
This crate serves as a wrapper around the AWS IoT SDK,
providing a convenient and idiomatic Rust interface for developers working with AWS IoT services.
"""

[dependencies]
aws-crt-cpp-sys.workspace = true
aws-iot-device-sdk-sys.workspace = true
aws-c-auth-sys.workspace = true
aws-c-cal-sys.workspace = true
aws-c-common-sys.workspace = true
aws-c-compression-sys.workspace = true
aws-c-event-stream-sys.workspace = true
aws-c-http-sys.workspace = true
aws-c-io-sys.workspace = true
aws-c-iot-sys.workspace = true
aws-c-mqtt-sys.workspace = true
aws-c-s3-sys.workspace = true
aws-c-sdkutils-sys.workspace = true

crossbeam = "0.8"
chrono = "0.4"
futures = "0.3"
itertools = "0.12"
parking_lot = "0.12"
pin-project = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smallvec = "1"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "chrono"] }

[build-dependencies]
cc = { version = "1", features = ["parallel"] }
