[package]
name = "beluga"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
description = """
Crate designed to simplify the integration of AWS IoT functionality into your Rust applications.
This crate serves as a wrapper around the AWS IoT SDK,
providing a convenient and idiomatic Rust interface for developers working with AWS IoT services.
"""

[dependencies]
aws-c-iot-sys = { git = "https://github.com/inomotech-foss/aws-iot-device-sdk-rust.git", rev = "111839819d1b10e0a576a97a07690d419f060d51" }
aws-crt-cpp-sys = { git = "https://github.com/inomotech-foss/aws-iot-device-sdk-rust.git", rev = "111839819d1b10e0a576a97a07690d419f060d51" }
aws-iot-device-sdk-sys = { git = "https://github.com/inomotech-foss/aws-iot-device-sdk-rust.git", rev = "111839819d1b10e0a576a97a07690d419f060d51" }
crossbeam = "0.8"
futures = "0.3"
itertools = "0.12"
parking_lot = "0.12"
pin-project = "1"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter", "chrono"] }

[build-dependencies]
cc = { version = "1", features = ["parallel"] }
