/* automatically generated by rust-bindgen 0.69.1 */

extern "C" {
    #[doc = " The entry point function to perform a CRC32 (Ethernet, gzip) computation.\n Selects a suitable implementation based on hardware capabilities.\n Pass 0 in the previousCrc32 parameter as an initial value unless continuing\n to update a running crc in a subsequent call."]
    pub fn aws_checksums_crc32(
        input: *const u8,
        length: ::core::ffi::c_int,
        previousCrc32: u32,
    ) -> u32;
    #[doc = " The entry point function to perform a Castagnoli CRC32c (iSCSI) computation.\n Selects a suitable implementation based on hardware capabilities.\n Pass 0 in the previousCrc32 parameter as an initial value unless continuing\n to update a running crc in a subsequent call."]
    pub fn aws_checksums_crc32c(
        input: *const u8,
        length: ::core::ffi::c_int,
        previousCrc32: u32,
    ) -> u32;
}
