name: CI

on:
  push:
    branches: [main, simon/aws-crt]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-version: [1.74, stable]
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: hecrj/setup-rust-action@v2
        with:
          rust-version: ${{ matrix.rust-version }}
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - uses: actions/checkout@v4
      - run: cargo nextest run --all-features
